### ISSUE TITLE
A little doubt about the test time

### ISSUE THREAD

**Issue by LT-ZHONG** [Shiaoming/stair-perception#3]
Hi authors,

This stairs-perception project is really interesting and amazing.
My Ubuntu 16.04 equips with an i5-8600K 3.6GHz CPU and I tested the project with the pcd file provided in the "sample" folder.

![19](https://user-images.githubusercontent.com/49059253/85823583-5bc53780-b7b0-11ea-9ab7-802989202e69.png)

As you can see from the picture, the total consuming time was 200ms around, which is quite different from the test time given in your paper.

![image](https://user-images.githubusercontent.com/49059253/85823861-f6be1180-b7b0-11ea-9db3-ec26786753b8.png)

I am really confused about that because the CPU on my computer seems better than the CPU used in the paper but achieved slower results. I wonder if you used GPU to achieve that speed or some other acceleration techniques?

Thanks anyway.

**Comment by Shiaoming** [comment]
@LT-ZHONG
Hi, I'm glad that this project might be useful for you.

First of all, no GPU acceleration techniques were used in this project. 

In fact, among all the steps, the cloud normal estimation and plane segmentation are the most computational cost steps. In order to speed up this process, in the original paper, we downsampled the RGBD data from `512 x 424` to `128 x 106` (ref Sec. 2.1.1), and the 3D voxel was set to `0.01m x 0.01m x 0.02m` (ref Sec. 2.1.4). However, for better visualization, the cloud files in the `samples` folder are created from RGBD data with resolution `512 x 424`, and the default voxel in `param.yaml` is set to `0.01m x 0.01m x 0.01m`. So that's the difference.

Moreover, the sample cloud `0001_cloud.pcd` almost observes all the steps of the stair, which will increase the computation of plane segmentation. It's must be pointed out that if we mount the Kinect on the belly observing the forward steps for a lower limb exoskeleton, the Kinect can only observe three steps at most, which was the data we actually tested in the paper.

BTW, to address the plane segmentation problem, we later adopted a fast plane extraction method for organized point cloud, please refer [this](https://doi.org/10.1063/1.5109741). We also open-sourced the code [here](https://github.com/Shiaoming/stair-perception-ROS) (**Note that the code seems to be buggy after I upgraded Ubuntu to 18.04**.)

Cheers~

**Comment by LT-ZHONG** [comment]
@Shiaoming 
Thanks for your replying.

But unfortunately, I still cannot find the code where you down sampled the RGBD data from Kinect. 
According to the paper(Sec. 2.1.1), the "down sampling" process should be prior to the "rotating point cloud" process. 
I noticed that there are functions called `pk2g->get(color_img, depth_img, cloud_in);` and  `rotationCloudPoints(*cloud_in, rotation_matrix, *cloud);` in `read.cpp`.  I guess that should be the functions dealing with data coming from Kinect. And I read thoroughly the code but still cannot figure out how did the data be sampled to `128 x 106`

> https://github.com/Shiaoming/stair-perception/blob/9c41809deeca215fd7c84b1567ba4c8dec087f3d/test/reader.cpp#L374

> https://github.com/Shiaoming/stair-perception/blob/9c41809deeca215fd7c84b1567ba4c8dec087f3d/test/reader.cpp#L387

Would you please explain how the data is down sampled ?

**Comment by Shiaoming** [comment]
@LT-ZHONG
Please check these code fragments:
> https://github.com/Shiaoming/stair-perception/blob/9c41809deeca215fd7c84b1567ba4c8dec087f3d/modules/stairperception/StairPerception.cpp#L29

> https://github.com/Shiaoming/stair-perception/blob/9c41809deeca215fd7c84b1567ba4c8dec087f3d/modules/stairperception/StairPerception.cpp#L298-L301

**Comment by LT-ZHONG** [comment]
@Shiaoming 

Thank you for replying. Your answer really helped me a lot.

BTW, I think I found a little mistake, which is in the function `StairDetection::removeClosetPoints`

> https://github.com/Shiaoming/stair-perception/blob/9c41809deeca215fd7c84b1567ba4c8dec087f3d/modules/stairperception/StairPerception.cpp#L627

I guess you just want to check the distance of the points from the origin, and the distance formula is `x*x + y*y + z*z`

Sorry if I misunderstood your meaning.

**Comment by Shiaoming** [comment]
@LT-ZHONG

Yes, It's a typo. 

Thank you for your correction, and any suggestions for improvement are welcome. :raised_hands:
